---
title: "01: Diversidade genética em genótipos de linho (Linum usitatissimum, L.) cultivados em Florianópolis-SC"
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```


# Pacotes


```{r warning=FALSE, message=FALSE}
library(pliman)
library(tidyverse)
library(purrr)
library(rio)
set_wd_here("figs/capsulas")
img <- image_import("5ae8b265-9e47-4b8e-8188-add077c06ceb.jpg")
res <- 
  analyze_objects(
    img,
    resize = 50,
    index = "GRAY",
    marker = "point",
    marker_col = "red",
    opening = 10,
    filter = 2
  )

```

# Contagem manual
```{r}
pick_count(img)

```



# Analisar as fotos

# Processamento em lote (validação)


```{r}
res_val <- 
  analyze_objects(
    pattern = "-",
    resize = 50,
    dir_original = "figs/capsulas/",
    dir_processed = "figs/proc",
    index = "GRAY",
    marker = "point",
    marker_col = "red",
    save_image = TRUE,
    opening = 15,
    filter = 3,
    parallel = TRUE,
    workers = 6
  )
export(res_val$count, "data/capsulas.xlsx")
res_graos <- 
  analyze_objects(
    pattern = "-",
    resize = 50,
    dir_original = "figs/graos/",
    dir_processed = "figs/proc_graos",
    index = "GRAY",
    marker = "point",
    marker_col = "red",
    save_image = TRUE,
    marker_size = 1,
    show_contour = FALSE,
    opening = 7,
    parallel = TRUE,
    workers = 6
  )
export(res_val$count, "data/graos.xlsx")
export(res_val$results, "data/graos_raw.csv")
```



# Cenário 100%
```{r}
# CENÁRIO COM IMAGENS ORIGINAIS
cenarios <- expand_grid(open = c(0, 25),
                        filt = c(0, 5))
results_100 <- 
  map_dfr(1:4, function(i){
    tp <- 
      system.time(
        res <- 
          analyze_objects(
            pattern = "-",
            dir_original = "figs/R100/",
            index = "GRAY",
            opening = cenarios[[i, 1]],
            filter = cenarios[[i, 2]],
            plot = FALSE
          )
      )
    res$count |> 
      mutate(filter = cenarios[[i, 2]],
             opening = cenarios[[i, 1]],
             resolucao = "100",
             tempo = as.numeric(tp)[3])
    
  })



# 50% DA RESOLUÇÃO

cenarios <- expand_grid(open = c(0, 15),
                        filt = c(0, 3))

results_50 <- 
  map_dfr(1:4, function(i){
    tp <- 
      system.time(
        res <- 
          analyze_objects(
            pattern = "-",
            dir_original = "figs/R50/",
            index = "GRAY",
            opening = cenarios[[i, 1]],
            filter = cenarios[[i, 2]],
            plot = FALSE
          )
      )
    res$count |> 
      mutate(filter = cenarios[[i, 2]],
             opening = cenarios[[i, 1]],
             resolucao = "50",
             tempo = as.numeric(tp)[3])
    
  })

# 25% DA RESOLUÇÃO
cenarios <- expand_grid(open = c(0, 5),
                        filt = c(0, 2))

results_25 <- 
  map_dfr(1:4, function(i){
    tp <- 
      system.time(
        res <- 
          analyze_objects(
            pattern = "-",
            dir_original = "figs/R25/",
            index = "GRAY",
            opening = cenarios[[i, 1]],
            filter = cenarios[[i, 2]],
            plot = FALSE
          )
      )
    res$count |> 
      mutate(filter = cenarios[[i, 2]],
             opening = cenarios[[i, 1]],
             resolucao = "25",
             tempo = as.numeric(tp)[3])
    
  })

final <- bind_rows(results_100, results_50, results_25)
export(final, "dados_cenarios.xlsx")
```




# Section info
```{r}
sessionInfo()
```

