---
  title: ""
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```


# Pacotes

```{r warning=FALSE, message=FALSE}
library(rio)
library(tidyverse)
library(metan)
library(ggridges)
df <- import_list("data/progresso.xlsx")
g2022 <- df$`2022` |> select(GEN, RGPLA) |> rename(A2022 = RGPLA)
g2023 <- df$`2023` |> select(GEN, RGPLA) |> rename(A2023 = RGPLA)
g2024 <- df$`2024` |> select(GEN, RGPLA) |> rename(A2024 = RGPLA)


dfge <- 
  reduce(list(g2024, g2023, g2022), left_join) |> 
  remove_rows_na()

df_ggplot <- 
  dfge |> 
  pivot_longer(-GEN, names_to = "AMB", values_to = "RGPLA") |> 
  filter(GEN %in% c("G1", "G11"))

ggplot(df_ggplot, aes(x = AMB, y = RGPLA, fill = GEN)) +
  geom_col(position = position_dodge())
```



# Interação genótipo ambiente

$$
y_{ij} = m + g_i + a_j + (ga)_{ij}
$$

$$
\hat{g_i} = \bar{g_i} - m  \\
\hat{a_j} = \bar{a_j} - m  
$$
$$
\hat{(ga)_{ij}} = y_{ij} - m - \hat{g_i} - \hat{a_j} \\
\hat{(ga)_{ij}} = y_{ij} - \bar{g_i} - \bar{a_j} + m
$$


```{r}
matga <- dfge |> column_to_rownames("GEN") |> as.matrix()
m <- mean(matga)

# ESTIMANDO O EFEITO DA INTERAÇÃO
mat_ef <- matrix(NA, ncol = ncol(matga), nrow = nrow(matga))

for(i in 1:nrow(matga)){
  egi <- mean(matga[i, ]) - m
  for(j in 1:ncol(matga)){
    eaj <- mean(matga[, j]) - m
    mat_ef[i, j] <- matga[i, j] - m - egi - eaj
  }
}
colnames(mat_ef) <- colnames(matga)
rownames(mat_ef) <- rownames(matga)


# criar um mapa de calor
dfggp <- 
mat_ef |> 
  as.data.frame() |> 
  tibble::rownames_to_column("gen") |> 
  pivot_longer(-gen, names_to = "amb", values_to = "rg")

phm <- 
ggplot(dfggp, aes(amb, gen, fill = rg))+
  geom_tile() +
  scale_fill_viridis_c()


```

# Método WAAS
```{r}

mod <- waas_means(df_ggplot, AMB, GEN, RGPLA)
waas_vals <- get_model_data(mod)
p1 <- plot_scores(mod, type = 2)
library(patchwork)
phm + p1


plot_waasby(mod)
```

## Método Wricke
```{r}
ecovalencia <- 
  apply(mat_ef, 1, function(x){
    sum(x^2)
  })
eco <- data.frame(ecovalencia) |> rownames_to_column("GEN")
stabs <- left_join(waas_vals, eco)
corr_plot(stabs)
```

## stabilidade 
```{r}
pwaas <- plot_scores(mod, type = 3)
phm + pwaas
```

## Performance e stabilidade
```{r}
plot_waasby(mod)

```

# Section info
```{r}
sessionInfo()
```

