---
title: "04: Trilha"
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```


# Pacotes

```{r warning=FALSE, message=FALSE}
library(rio)
library(tidyverse)
library(metan)

planta <- 
  import("data/dados_labfoto.xlsx") |> 
  select(UNIQUE_ID, GEN, PLANTA:NG, -NPT) |> 
  remove_rows_na() |> 
  mutate(MMG = MG / NG * 1000,
         ICC = MG / MC)


ggplot(planta, aes(NG, MG)) +
  geom_point()
# bindar as informações dos grãos

graos <- 
  import("data/graos_raw.csv") |> 
  group_by(img) |> 
  summarise(
    ELGRA = mean(elongation)
  ) |> 
  rename(UNIQUE_ID = img)

capsulas <- 
  import("data/capsulas_raw.csv") |> 
  group_by(img) |> 
  summarise(
    ELCAP = mean(elongation)
  ) |> 
  rename(UNIQUE_ID = img)

dfplantas <- reduce(list(planta, graos, capsulas), left_join)

dfmedias <- 
  dfplantas |> 
  group_by(GEN) |> 
  summarise(across(where(is.numeric), \(x){mean(x, na.rm = TRUE)})) |> 
  remove_rows_na()

```


# Diagnóstico da multicolinearidade
```{r}
colin_plantas <- colindiag(dfplantas, -MG)
colin_medias <- colindiag(dfmedias, - MG)

coldiag <- 
  colin_plantas$VIF |> rename(VIF_PLANTA = VIF) |> 
  left_join(
    colin_medias$VIF |> rename(VIF_MEDIA = VIF)
  )

coldiag1 <-
  colindiag(dfmedias, -c(MG,NC,NG)) #mg, nc, ng


 det(as.matrix(colin_medias$cormat))

```


# Trilha
## Sem nenhuma correção

```{r}
trilha1_planta <- path_coeff(dfplantas, 
                             resp = MG,
                             pred = everything())
plot(trilha1_planta)


trilha1_media <- path_coeff(dfmedias, 
                            resp = MG,
                            correction = 0.1,
                            pred = everything())

plot(trilha1_media)
```

#Regressão em crista
#Diagonal Direto, linha indireto
#DIreto -> efeito puro da variável, soma da linha -> pearson.
#VIF, menor que 10
#Condição(Razão maior e menor abaixo de 100, )
#Determinante quanto menor, mais problemático


## Estimando os coeficientes
```{r}
library(metan)
cor.x <- as.matrix(colin_medias$cormat)
correl <- corr_coef(dfmedias)
cor.y <- as.vector(corr_focus(correl, MG)$MG)

direto <- solve(cor.x %*% t(cor.x)) %*% cor.x %*% cor.y
n <- ncol(cor.x)
Coeff <- data.frame(cor.x)
for (i in 1:n) {
  for (j in 1:n) {
    Coeff[i, j] <- direto[j] * cor.x[i, j]
  }
}
Coeff
```


## Seleção de variáveis
```{r}
trilha2_planta <- 
  path_coeff(dfplantas, 
             resp = MG,
             pred = everything(),
             brutstep = TRUE)

plot(trilha2_planta$Models$Model_1)


trilha2_media <- 
  path_coeff(dfmedias, 
             resp = MG,
             pred = everything(),
             brutstep = TRUE)

plot(trilha2_planta$Models$Model_1)
```


# Section info
```{r}
sessionInfo()

```

